### ISSUE TITLE
demo version

### ISSUE THREAD

**Issue by xiggeush** [CrystalVulpine/forum#1]
I suggest to put a demo version of the forum somewhere.

**Comment by CrystalVulpine** [comment]
I can't right now. For one, the database isn't exactly in working condition. It'll work if you keep using the same version but as soon as you need to add attributes to objects it has to be completely recreated. It's also a test `db.session` and not a real db.

The other thing is, github pages can't host databases to my knowledge, only static websites. I would have to spend money on a domain *and* hosting (since I don't have a server computer that's turned on all the time), and since this is just a silly project I don't think that's worth it. If it evolves into something more serious I'll look into it, but for now it's probably not going to happen.

**Comment by xiggeush** [comment]
As for hosting, you can try [pythonanywhere](https://www.pythonanywhere.com/).

**Comment by CrystalVulpine** [comment]
I can try that but I'll have to figure out the database first.
